# Setup
name:         My life as a Solution Architect
tagline:      A blog about the life, the universe and everything about Solution Architecture
baseurl:      "https://solution-architect.blog/"
url:          "https://solution-architect.blog/"
locale:       "en"
description: This blog is about solution architecture, how to get a job, how to be a solution architect, best practises for all the topics and all the rest.
page_excerpts    : true
permalink: /:slugified_categories/:slug
defaults:            
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout              : "post"
# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

#Others
markdown: kramdown
