# Setup
name:         My life as a Solution Architect
tagline:      A blog about the <a href="/life/" title="The life of a solution architect">life</a>, the <a href="/universe/" title="The universe of a solution architect, the tools, the methods">universe</a> and <a href="/everything/" title="everything about solution architecture">everything about Solution Architecture</a>
url:      "https://solution-architect.blog"
locale:       "en"
description: This blog is about solution architecture, how to get a job, how to be a solution architect, best practises for all the topics and all the rest.
page_excerpts    : true
permalink: /:slugified_categories/:slug
jekyll-archives:
  enabled:
    - categories
  layout: category
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/:name/'
defaults:            
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout              : "post"
# Gems
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-tagging-related_posts

#Others
markdown: kramdown
