# Setup
name:         My live as a Solution Architect
tagline:      A blog about the life, the universe and everything about Solution Architecture
baseurl:      ""
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
